# Generated by Django 2.2 on 2021-05-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20210527_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='confirmar',
            field=models.BooleanField(default=False),
        ),
    ]
