# Generated by Django 2.2 on 2021-06-03 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20210603_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraproducto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
