# Generated by Django 2.2 on 2021-06-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_compraproducto_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='confirmar',
        ),
    ]
